name: Update Status

on:
  schedule:
    - cron: "*/7 * * * *"
  workflow_dispatch:
jobs:
  updatestatus:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner.

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8 #install the python needed

      - name: execute py script
        run: |
          python -m pip install --upgrade pip
          pip install requests
          python scrape.py

      - name: Check if status was updated
        id: verify_diff
        run: |
          git diff --quiet status.json || echo "::set-output name=new_status_exist::true"

      - name: Commit files
        if: steps.verify_diff.outputs.new_status_exist == 'true'
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add status.json
          git commit -m "status updated"
          git push
